export const CATEGORY_NAMES: Record<string, string> = {
  "cs.AI": "Artificial Intelligence",
  "cs.LG": "Machine Learning",
  "cs.CL": "Computation & Language",
  "cs.CV": "Computer Vision",
  "cs.IR": "Information Retrieval",
  "cs.RO": "Robotics",
  "cs.MA": "Multiagent Systems",
  "cs.NE": "Neural & Evolutionary",
  "stat.ML": "Statistical ML",
  "cs.CR": "Cryptography & Security",
  "cs.SE": "Software Engineering",
  "cs.HC": "Human-Computer Interaction",
  "eess.AS": "Audio & Speech",
  "eess.IV": "Image & Video Processing",
  "cs.SD": "Sound",
  "cs.CY": "Computers & Society",
  "cs.PL": "Programming Languages",
  "cs.GR": "Graphics",
  "cs.DC": "Distributed Computing",
  "cs.SI": "Social & Information Networks",
  "cs.MM": "Multimedia",
  "cs.AR": "Hardware Architecture",
  "cs.DB": "Databases",
  "cs.IT": "Information Theory",
  "cs.CE": "Computational Engineering",
  "cs.GT": "Game Theory",
  "cs.DS": "Data Structures & Algorithms",
  "cs.CC": "Computational Complexity",
  "cs.PF": "Performance",
  "cs.OS": "Operating Systems",
  "cs.NI": "Networking",
  "cs.FL": "Formal Languages",
  "cs.DL": "Digital Libraries",
  "cs.CG": "Computational Geometry",
  "cs.LO": "Logic in CS",
  "cs.ET": "Emerging Technologies",
  "cs.SC": "Symbolic Computation",
  "cs.SY": "Systems & Control",
  "cs.NA": "Numerical Analysis",
  "cs.GL": "General Literature",
  "cs.OH": "Other CS",
  "cs.MS": "Mathematical Software",
  "eess.SP": "Signal Processing",
  "eess.SY": "Systems & Control",
  "stat.ME": "Statistical Methodology",
  "stat.CO": "Statistical Computation",
  "stat.AP": "Applied Statistics",
  "stat.TH": "Statistics Theory",
  "stat.OT": "Other Statistics",
  "math.OC": "Optimization & Control",
  "math.ST": "Statistics Theory",
  "math.NA": "Numerical Analysis",
  "math.PR": "Probability",
  "math.HO": "History of Mathematics",
  "math.DS": "Dynamical Systems",
  "math.AP": "Analysis of PDEs",
  "math.IT": "Information Theory",
  "math.CO": "Combinatorics",
  "quant-ph": "Quantum Physics",
  "hep-ph": "High Energy Physics",
  "cond-mat.mtrl-sci": "Materials Science",
  "cond-mat.dis-nn": "Disordered Systems & Neural Networks",
  "cond-mat.soft": "Soft Matter",
  "cond-mat.stat-mech": "Statistical Mechanics",
  "physics.soc-ph": "Physics & Society",
  "physics.ao-ph": "Atmospheric & Oceanic Physics",
  "physics.optics": "Optics",
  "physics.data-an": "Data Analysis & Statistics",
  "physics.comp-ph": "Computational Physics",
  "q-bio.QM": "Quantitative Methods (Bio)",
  "q-bio.NC": "Neurons & Cognition",
  "q-bio.BM": "Biomolecules",
  "q-bio.GN": "Genomics",
  "q-fin.GN": "General Finance",
  "q-fin.RM": "Risk Management",
  "q-fin.CP": "Computational Finance",
  "q-fin.ST": "Statistical Finance",
  "econ.GN": "General Economics",
  "econ.EM": "Econometrics",
  "astro-ph.SR": "Solar & Stellar Astrophysics",
  "astro-ph.IM": "Astrophysics Instrumentation",
  "astro-ph.CO": "Cosmology",
};

export const categoryName = (c: string) => CATEGORY_NAMES[c] ?? c;

export const formatCount = (n: number) =>
  n >= 1000 ? `${(n / 1000).toFixed(n >= 10_000 ? 0 : 1)}k` : String(n);

/** "2017-06-12" → "12 Jun 2017", the way arXiv prints dates. */
export const formatArxivDate = (iso: string) =>
  new Date(iso).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" });

/** "Ashish Vaswani" → "A. Vaswani", as in a reference list. */
export const initials = (name: string) => {
  const parts = name.trim().split(/\s+/);
  if (parts.length < 2) return name;
  const last = parts.pop();
  return `${parts.map((p) => `${p[0]}.`).join(" ")} ${last}`;
};
